### PR TITLE
Add other assay

### PR DESCRIPTION
**Pull request by afwillia**

### CODE REVIEW

**Comment by afwillia** [comment]
I want to add a fourth test data component. I took "other assay" from the HTAN data model and trimmed its required columns to Filename and File Type.

**Comment by GiaJordan** [comment]
@afwillia is the convert CI pulling from the latest released version of schematic or `develop`?

**Review by GiaJordan — APPROVED** [review]

**Comment by GiaJordan** [comment]
Also, should we update the schematic repo example model to match this one?

**Comment by afwillia** [comment]
@GiaJordan the CI pulls from schematic's develop branch. Good idea to keep everything in sync. But I don't think it's strictly necessary, especially since I noticed @mialy-defelice has been updating schematic's example model for testing.

**Pull request merged**
